remote_theme: aterenin/minima-reboot
head_inline: "<style>#nav-header { height: 0;opacity: 0; }</style>"
title: wordboom

header_pages:
  - Math.md

# plugins:
#   - jekyll-relative-links
# relative_links:
#   enabled: true
#   collections: true
include:
  - Math.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
