remote_theme: aterenin/minima-reboot
head_inline: "<style>td:first-child { width: 7rem; }</style>"
title: wordboom
header_pages: ''
# plugins:
#   - jekyll-relative-links
# relative_links:
#   enabled: true
#   collections: true
include:
  - Math.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
