remote_theme: aterenin/minima-reboot
title: wordboom

header_pages:
  - Math.md

footer_icons:
  - username: Winky
    url: https://github.com/yuanyazhen/mp-wordboom

# plugins:
#   - jekyll-relative-links
# relative_links:
#   enabled: true
#   collections: true
include:
  - Math_Basic.md
  - MATH_Equation.md
  - punctuation_basic.md
  - computer_devices.md
  - computer_OSI_model.html
  - computer_binary_tree.md
  - idiom_colors.md
