remote_theme: aterenin/minima-reboot
title: wordboom

header_pages:
  - Math.md

footer_icons:
  - username: Winky
    url: https://github.com/yuanyazhen/mp-wordboom

# plugins:
#   - jekyll-relative-links
# relative_links:
#   enabled: true
#   collections: true
include:
  - "./MATH/*"
  - MATH/Math_Basic.md
  - Math.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
